### ISSUE TITLE
Windows scheduler log help

### ISSUE THREAD

**Issue by FrozenBeard** [thatjpk/cloudflare-ddns#2]
I have this setup on a scheduler on my home windows sever box to just run cloudflare-ddns.py, I set the path of Python and pass the script as a parameter via the scheduler.
Do I need to set the path to config? I also assume this is why im not getting a log output, as Im not sure how to set this in the scheduler.

**Comment by thatjpk** [comment]
Hm, I've never tried it on Windows but it should probably work. Since this script's logging is just printing to stdout and stuff, you have to redirect it to a file. I'm not sure where the Windows scheduler sends stdout or if you can configure anything about that.

However, instead of trying to get the scheduler to run the script directly you could probably wrap the invocation of the script in a batch file, do the logging redirection in there, and make the scheduled task run the batch file. Something like:

```
@ECHO off
C:\path\to\python.exe C:\path\to\cloudflare-ddns.py C:\path\to\config.yaml >> C:\path\to\cloudflare_ddns.log
```

Fix up the paths, then set the scheduler to run something like that.  Fair warning: I haven't actually tried it, but I think it'll work.  If it doesn't, I'll give it a shot on my Windows machine to see what's up.

HTH!

**Comment by thatjpk** [comment]
Gonna go ahead and close this.  If you need any further assistance, feel free to reopen!
